// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCss337XcRDBpFT5ghd_6ddkz0x1O6HJK8',
    appId: '1:532533031917:web:ce7039b74cb6c27b9f6de4',
    messagingSenderId: '532533031917',
    projectId: 'upi-pay-app',
    authDomain: 'upi-pay-app.firebaseapp.com',
    storageBucket: 'upi-pay-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCss337XcRDBpFT5ghd_6ddkz0x1O6HJK8',
    appId: '1:532533031917:android:ce7039b74cb6c27b9f6de4',
    messagingSenderId: '532533031917',
    projectId: 'upi-pay-app',
    storageBucket: 'upi-pay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCss337XcRDBpFT5ghd_6ddkz0x1O6HJK8',
    appId: '1:532533031917:web:ce7039b74cb6c27b9f6de4',
    messagingSenderId: '532533031917',
    projectId: 'upi-pay-app',
    authDomain: 'upi-pay-app.firebaseapp.com',
    storageBucket: 'upi-pay-app.firebasestorage.app',
  );
}
